version: 2
updates:
- package-ecosystem: npm
  directory: "/src"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: dropbox
    versions:
    - 9.2.0
    - 9.4.0
  - dependency-name: nanoid
    versions:
    - 3.1.21
  - dependency-name: mocha
    versions:
    - 8.3.1
  - dependency-name: chai
    versions:
    - 4.3.3
  - dependency-name: node-stream-zip
    versions:
    - 1.13.2
